spring.application.name=clothing-store
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/vexalstock
spring.datasource.username=postgres
spring.datasource.password=7890
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
=======
>>>>>>> 1036410d51d2549b1d6af1f3de3eb884d386f849
